name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: ".tests/edge_case_test.py"
      id: tests-edge-case-test-py
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 5
        setup-command: ''
    - name: ".tests/leibniz_series_test.py"
      id: tests-leibniz-series-test-py
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 5
        setup-command: ''
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TESTS-EDGE-CASE-TEST-PY_RESULTS: "${{steps.tests-edge-case-test-py.outputs.result}}"
        TESTS-LEIBNIZ-SERIES-TEST-PY_RESULTS: "${{steps.tests-leibniz-series-test-py.outputs.result}}"
      with:
        runners: tests-edge-case-test-py, tests-leibniz-series-test-py
